# 可以尝试集成 config-server 中心来配置

spring:
  application:
    name: platform-gateway
  redis:
    host: localhost
    port: 6379
    database: 0
  main:
    allow-bean-definition-overriding: true
  zipkin:
    base-url: http://ZIPKIN-SERVER/
    discovery-client-enabled: true
    locator:
      discovery:
        enabled: true
  sleuth:
    sampler:
      probability: 1
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            # 返回的资源共享给请求来源
            allowed-origins:
              - "http://localhost:8080"
              - "http://shop.z.mukewang.com:8080"
              - "http://center.z.mukewang.com:8080"
              - "http://shop.z.mukewang.com"
              - "http://center.z.mukewang.com"
              - "*"
            # 允许携带认证信息 比如 cookie authorization
            allow-credentials: true
            allowed-headers: "*"
            allowed-methods: "*"
            expose-headers: "*"
            # 表示options可以在浏览器缓存多久
            max-age: 600
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
server:
  port: 20004

# eureka 配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:20000/eureka/


# 开启所有的actuator-endpoint
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
        # include: health, info, ...
  security:
    enable: false